# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-29 10:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transcription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(default='-', max_length=10, verbose_name='Unique short metadata item identifier (10 characters max)')),
            ],
        ),
    ]
