# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-29 12:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transcription', '0002_fieldchoice_helpchoice'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Transcription',
            new_name='Descriptor',
        ),
    ]
